/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package calculator;

import java.io.BufferedReader;
import java.io.File;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import javax.swing.JFrame;

/**
 *
 * @author 84708
 */
public class CalculatorForm extends javax.swing.JPanel {

    /**
     * Creates new form CalculatorForm
     */
    public CalculatorForm() {
        initComponents();
    }
    Boolean tinh=false;
    String[] ls= new String[30]; int i=0;
    PrintWriter pw;
    double a,b;
    String temp;
    String temp2;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtMainBox = new javax.swing.JTextField();
        txtCloneBox = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnNum1 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnCong = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnDoiDau = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnCham = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        btnCanBac2 = new javax.swing.JButton();
        btnMu2 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClearn = new javax.swing.JButton();
        btnPhanTram = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btn1PhanX = new javax.swing.JButton();
        btnBang = new javax.swing.JButton();
        btnLichSu = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(400, 350));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Casio");

        txtMainBox.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        txtMainBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMainBox.setName(""); // NOI18N

        txtCloneBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCloneBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCloneBox.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCloneBox)
                    .addComponent(txtMainBox))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCloneBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMainBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        txtMainBox.getAccessibleContext().setAccessibleName("txtMainBox");
        txtCloneBox.getAccessibleContext().setAccessibleName("txtCloneBox");

        jPanel2.setLayout(new java.awt.GridLayout(6, 4));

        btnNum1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNum1.setText("1");
        btnNum1.setName(""); // NOI18N
        btnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNum1);

        btnNum2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNum2.setText("2");
        btnNum2.setName(""); // NOI18N
        btnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNum2);
        btnNum2.getAccessibleContext().setAccessibleName("btnNum2");

        btnNum3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNum3.setText("3");
        btnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNum3);
        btnNum3.getAccessibleContext().setAccessibleName("btnNum3");

        btnCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCong.setText("+");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });
        jPanel2.add(btnCong);
        btnCong.getAccessibleContext().setAccessibleName("btnCong");

        btnNum4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNum4.setText("4");
        btnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNum4);
        btnNum4.getAccessibleContext().setAccessibleName("btnNum4");

        btnNum5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNum5.setText("5");
        btnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNum5);
        btnNum5.getAccessibleContext().setAccessibleName("btnNum5");

        btnNum6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNum6.setText("6");
        btnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum6ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNum6);
        btnNum6.getAccessibleContext().setAccessibleName("btnNum6");

        btnTru.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTru.setText("-");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });
        jPanel2.add(btnTru);
        btnTru.getAccessibleContext().setAccessibleName("btnTru");

        btnNum7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNum7.setText("7");
        btnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum7ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNum7);
        btnNum7.getAccessibleContext().setAccessibleName("btnNum7");

        btnNum8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNum8.setText("8");
        btnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum8ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNum8);
        btnNum8.getAccessibleContext().setAccessibleName("btnNum8");

        btnNum9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNum9.setText("9");
        btnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum9ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNum9);
        btnNum9.getAccessibleContext().setAccessibleName("btnNum9");

        btnNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNhan.setText("x");
        btnNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhan);
        btnNhan.getAccessibleContext().setAccessibleName("btnNhan");

        btnDoiDau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDoiDau.setText("+/-");
        btnDoiDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiDauActionPerformed(evt);
            }
        });
        jPanel2.add(btnDoiDau);
        btnDoiDau.getAccessibleContext().setAccessibleName("btnDoiDau");

        btnNum0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNum0.setText("0");
        btnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum0ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNum0);
        btnNum0.getAccessibleContext().setAccessibleName("btnNum0");

        btnCham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCham.setText(".");
        btnCham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamActionPerformed(evt);
            }
        });
        jPanel2.add(btnCham);
        btnCham.getAccessibleContext().setAccessibleName("btnCham");

        btnChia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChia.setText("÷");
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaActionPerformed(evt);
            }
        });
        jPanel2.add(btnChia);
        btnChia.getAccessibleContext().setAccessibleName("btnChia");

        btnCanBac2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCanBac2.setText("√");
        btnCanBac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanBac2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCanBac2);
        btnCanBac2.getAccessibleContext().setAccessibleName("btnCanBac2");

        btnMu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMu2.setText("x²");
        btnMu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMu2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnMu2);
        btnMu2.getAccessibleContext().setAccessibleName("btnMu2");

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("DEL");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);
        btnDelete.getAccessibleContext().setAccessibleName("btnDelete");

        btnClearn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClearn.setForeground(new java.awt.Color(255, 0, 0));
        btnClearn.setText("C");
        btnClearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearnActionPerformed(evt);
            }
        });
        jPanel2.add(btnClearn);
        btnClearn.getAccessibleContext().setAccessibleName("btnClearn");

        btnPhanTram.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPhanTram.setText("%");
        btnPhanTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanTramActionPerformed(evt);
            }
        });
        jPanel2.add(btnPhanTram);
        btnPhanTram.getAccessibleContext().setAccessibleName("btnPhanTram");

        btnUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUp.setText("00.0←");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });
        jPanel2.add(btnUp);
        btnUp.getAccessibleContext().setAccessibleName("btnUp");

        btn1PhanX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn1PhanX.setText("1/x");
        btn1PhanX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1PhanXActionPerformed(evt);
            }
        });
        jPanel2.add(btn1PhanX);
        btn1PhanX.getAccessibleContext().setAccessibleName("btnMotPhanX");

        btnBang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBang.setText("=");
        btnBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangActionPerformed(evt);
            }
        });
        jPanel2.add(btnBang);
        btnBang.getAccessibleContext().setAccessibleName("btnKetQua");

        btnLichSu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnLichSu.setText("Lịch sử");
        btnLichSu.setFocusPainted(false);
        btnLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichSuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLichSu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLichSu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum1ActionPerformed
        // TODO add your handling code here
            txtMainBox.setText(txtMainBox.getText()+ "1");
        if(tinh==true){
            txtMainBox.setText("");
            txtMainBox.setText(txtMainBox.getText()+ "1");
            tinh=false;
        }
    }//GEN-LAST:event_btnNum1ActionPerformed

    private void btnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum2ActionPerformed
        // TODO add your handling code here:

         txtMainBox.setText(txtMainBox.getText()+ "2");
        if(tinh==true){
            txtMainBox.setText("");
            txtMainBox.setText(txtMainBox.getText()+ "2");
            tinh=false;
        }
    }//GEN-LAST:event_btnNum2ActionPerformed

    private void btnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum3ActionPerformed
        // TODO add your handling code here:
            txtMainBox.setText(txtMainBox.getText()+ "3");
        if(tinh==true){
            txtMainBox.setText("");
            txtMainBox.setText(txtMainBox.getText()+ "3");
            tinh=false;
        }
    }//GEN-LAST:event_btnNum3ActionPerformed

    private void btnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum4ActionPerformed
        // TODO add your handling code here:
            txtMainBox.setText(txtMainBox.getText()+ "4");
        if(tinh==true){
            txtMainBox.setText("");
            txtMainBox.setText(txtMainBox.getText()+ "4");
            tinh=false;
        }
    }//GEN-LAST:event_btnNum4ActionPerformed

    private void btnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum5ActionPerformed
        // TODO add your handling code here:
            txtMainBox.setText(txtMainBox.getText()+ "5");
        if(tinh==true){
            txtMainBox.setText("");
            txtMainBox.setText(txtMainBox.getText()+ "5");
            tinh=false;
        }
    }//GEN-LAST:event_btnNum5ActionPerformed

    private void btnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum6ActionPerformed
        // TODO add your handling code here:
            txtMainBox.setText(txtMainBox.getText()+ "6");
        if(tinh==true){
            txtMainBox.setText("");
            txtMainBox.setText(txtMainBox.getText()+ "6");
            tinh=false;
        }
    }//GEN-LAST:event_btnNum6ActionPerformed

    private void btnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum7ActionPerformed
        // TODO add your handling code here:
            txtMainBox.setText(txtMainBox.getText()+ "7");
        if(tinh==true){
            txtMainBox.setText("");
            txtMainBox.setText(txtMainBox.getText()+ "7");
            tinh=false;
        }
    }//GEN-LAST:event_btnNum7ActionPerformed

    private void btnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum8ActionPerformed
        // TODO add your handling code here:
            txtMainBox.setText(txtMainBox.getText()+ "8");
        if(tinh==true){
            txtMainBox.setText("");
            txtMainBox.setText(txtMainBox.getText()+ "8");
            tinh=false;
        }
    }//GEN-LAST:event_btnNum8ActionPerformed

    private void btnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum9ActionPerformed
        // TODO add your handling code here:
            txtMainBox.setText(txtMainBox.getText()+ "9");
        if(tinh==true){
            txtMainBox.setText("");
            txtMainBox.setText(txtMainBox.getText()+ "9");
            tinh=false;
        }
    }//GEN-LAST:event_btnNum9ActionPerformed

    private void btnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum0ActionPerformed
        // TODO add your handling code here:
            txtMainBox.setText(txtMainBox.getText()+ "0");
        if(tinh==true){
            txtMainBox.setText("");
            txtMainBox.setText(txtMainBox.getText()+ "0");
            tinh=false;
        }
    }//GEN-LAST:event_btnNum0ActionPerformed

    private void btnDoiDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiDauActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        double so = Double.parseDouble(txtMainBox.getText());
        try{
            so = Double.parseDouble(txtMainBox.getText());
            so=-so;
            txtMainBox.setText(""+so);
        }catch(Exception e){
            e.printStackTrace();
        }
        LuuLichSu("(+/-) "+ (-so) +" = "+so);
    }//GEN-LAST:event_btnDoiDauActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        temp="+";
        txtCloneBox.setText(txtMainBox.getText() + " " +temp);
        a=Double.parseDouble(txtMainBox.getText());
        txtMainBox.setText("");
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        b=Double.parseDouble(txtMainBox.getText());
        if(temp=="+"){
            txtMainBox.setText(""+(a+b));
            LuuLichSu();
        }
        else if(temp=="-"){
            txtMainBox.setText(""+(a-b));
            LuuLichSu();
        }
        else if(temp=="x"){
            txtMainBox.setText(""+(a*b));
            LuuLichSu();
        }
        else if(temp=="÷"){
            txtMainBox.setText(""+(a/b));
            LuuLichSu();
        }
        txtCloneBox.setText("");
        tinh=true;
        
    }//GEN-LAST:event_btnBangActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        temp="-";
        txtCloneBox.setText(txtMainBox.getText() + " " +temp);
        a=Double.parseDouble(txtMainBox.getText());
        txtMainBox.setText("");
        
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        temp="x";
        txtCloneBox.setText(txtMainBox.getText() + " " +temp);
        a=Double.parseDouble(txtMainBox.getText());
        txtMainBox.setText("");
    }//GEN-LAST:event_btnNhanActionPerformed

    private void btnChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        temp="÷";
        txtCloneBox.setText(txtMainBox.getText() + " " +temp);
        a=Double.parseDouble(txtMainBox.getText());
        txtMainBox.setText("");
    }//GEN-LAST:event_btnChiaActionPerformed

    private void btnClearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearnActionPerformed
        // TODO add your handling code here:
        txtCloneBox.setText("");
        txtMainBox.setText("");
        a=0;b=0;temp="";
    }//GEN-LAST:event_btnClearnActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        String v1=txtMainBox.getText();
        String v2="";
        if(v1.length()==0){
            v1=" ";
        }
        else
            v2= v1.substring(0, v1.length()-1);
        txtMainBox.setText(v2);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnChamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamActionPerformed
        // TODO add your handling code here:
        if(temp!="1")
            txtMainBox.setText(txtMainBox.getText()+ ".");
        temp="1";  
    }//GEN-LAST:event_btnChamActionPerformed

    private void btnCanBac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanBac2ActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        temp="√";
        txtCloneBox.setText(" " +temp+ txtMainBox.getText());
        a=Double.parseDouble(txtMainBox.getText());
        double value= Math.sqrt(a);
        txtMainBox.setText(""+value);
        LuuLichSu(txtCloneBox.getText() +" = "+txtMainBox.getText());
    }//GEN-LAST:event_btnCanBac2ActionPerformed

    private void btnMu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMu2ActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        temp="²";
        txtCloneBox.setText(txtMainBox.getText()+temp);
        a=Double.parseDouble(txtMainBox.getText());
        double value= Math.pow(a, 2);
        txtMainBox.setText(""+value);
        LuuLichSu(txtCloneBox.getText() +" = "+txtMainBox.getText());
    }//GEN-LAST:event_btnMu2ActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        String s=txtMainBox.getText();
        a=Double.parseDouble(txtMainBox.getText());
        int vt= s.indexOf(".");
        int x= s.substring(vt).length()-1;
        double z=Math.pow(10, x-1);
        txtMainBox.setText(Math.ceil(a*z)/z+"");
        tinh=true;
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnPhanTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanTramActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        b= Double.parseDouble(txtMainBox.getText());
        if(txtCloneBox.getText()=="")
        {
            a=1;
        }
        if(b>0)
            txtMainBox.setText((a*b/100)+"");
    }//GEN-LAST:event_btnPhanTramActionPerformed
    private void LuuLichSu(){
        try{
            ls[i]=(a+" "+temp+" "+b+" = "+txtMainBox.getText()); i++;
            PrintWriter pw=new PrintWriter("lichsu.txt");
            for(int j=0; j<i; j++)
                pw.print(ls[j]+"\n");
            pw.close();
            System.out.print("Write successful!\n");
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    private void LuuLichSu(String s){
        try{
            ls[i]=s; i++;
            PrintWriter pw=new PrintWriter("lichsu.txt");
            for(int j=0; j<i; j++)
                pw.print(ls[j]+"\n");
            pw.close();
            System.out.print("Write successful!\n");
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    private void btnLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichSuActionPerformed
        // TODO add your handling code here:
        JFrame frame2= new JFrame();
        LichSu ls= new LichSu();
        frame2.add(ls);
        frame2.setSize(400, 450);
        frame2.setVisible(true); 
    }//GEN-LAST:event_btnLichSuActionPerformed

    private void btn1PhanXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1PhanXActionPerformed
        // TODO add your handling code here:
        if(txtMainBox.getText().equals(""))
            return;
        b= Double.parseDouble(txtMainBox.getText());
        txtMainBox.setText((1/b)+"");
        tinh=true;
        LuuLichSu("1/"+b+" = "+ txtMainBox.getText());
    }//GEN-LAST:event_btn1PhanXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1PhanX;
    private javax.swing.JButton btnBang;
    private javax.swing.JButton btnCanBac2;
    private javax.swing.JButton btnCham;
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnClearn;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDoiDau;
    private javax.swing.JButton btnLichSu;
    private javax.swing.JButton btnMu2;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnPhanTram;
    private javax.swing.JButton btnTru;
    private javax.swing.JButton btnUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCloneBox;
    private javax.swing.JTextField txtMainBox;
    // End of variables declaration//GEN-END:variables
}
